<?php

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 11,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 1',
                'file_name' => 'pulo cinta 1.png',
                'disk' => 'media',
                'size' => 415203,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 1,
                'created_at' => '2016-11-12 05:03:24',
                'updated_at' => '2016-11-12 05:03:24',
            ),
            1 => 
            array (
                'id' => 12,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 2',
                'file_name' => 'pulo cinta 2.jpg',
                'disk' => 'media',
                'size' => 359342,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 2,
                'created_at' => '2016-11-12 05:03:28',
                'updated_at' => '2016-11-12 05:03:28',
            ),
            2 => 
            array (
                'id' => 13,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 3',
                'file_name' => 'pulo cinta 3.jpg',
                'disk' => 'media',
                'size' => 404322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 3,
                'created_at' => '2016-11-12 05:03:32',
                'updated_at' => '2016-11-12 05:03:32',
            ),
            3 => 
            array (
                'id' => 14,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 4',
                'file_name' => 'pulo cinta 4.jpg',
                'disk' => 'media',
                'size' => 417741,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 4,
                'created_at' => '2016-11-12 05:03:44',
                'updated_at' => '2016-11-12 05:03:44',
            ),
            4 => 
            array (
                'id' => 15,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 5',
                'file_name' => 'pulo cinta 5.jpg',
                'disk' => 'media',
                'size' => 687729,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 5,
                'created_at' => '2016-11-12 05:03:47',
                'updated_at' => '2016-11-12 05:03:47',
            ),
            5 => 
            array (
                'id' => 16,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 6',
                'file_name' => 'pulo cinta 6.jpg',
                'disk' => 'media',
                'size' => 399670,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 6,
                'created_at' => '2016-11-12 05:03:51',
                'updated_at' => '2016-11-12 05:03:51',
            ),
            6 => 
            array (
                'id' => 17,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 1',
                'file_name' => 'olele 1.jpg',
                'disk' => 'media',
                'size' => 58030,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 7,
                'created_at' => '2016-11-12 05:04:28',
                'updated_at' => '2016-11-12 05:04:28',
            ),
            7 => 
            array (
                'id' => 18,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 2',
                'file_name' => 'olele 2.jpg',
                'disk' => 'media',
                'size' => 387887,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 8,
                'created_at' => '2016-11-12 05:04:32',
                'updated_at' => '2016-11-12 05:04:32',
            ),
            8 => 
            array (
                'id' => 19,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 3',
                'file_name' => 'olele 3.jpg',
                'disk' => 'media',
                'size' => 133272,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 9,
                'created_at' => '2016-11-12 05:04:35',
                'updated_at' => '2016-11-12 05:04:35',
            ),
            9 => 
            array (
                'id' => 20,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 4',
                'file_name' => 'olele 4.jpg',
                'disk' => 'media',
                'size' => 371159,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 10,
                'created_at' => '2016-11-12 05:04:38',
                'updated_at' => '2016-11-12 05:04:38',
            ),
            10 => 
            array (
                'id' => 21,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 5',
                'file_name' => 'olele 5.jpg',
                'disk' => 'media',
                'size' => 642926,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 11,
                'created_at' => '2016-11-12 05:04:41',
                'updated_at' => '2016-11-12 05:04:41',
            ),
            11 => 
            array (
                'id' => 22,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 6',
                'file_name' => 'olele 6.jpg',
                'disk' => 'media',
                'size' => 482974,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 12,
                'created_at' => '2016-11-12 05:04:45',
                'updated_at' => '2016-11-12 05:04:45',
            ),
            12 => 
            array (
                'id' => 23,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 7',
                'file_name' => 'olele 7.jpg',
                'disk' => 'media',
                'size' => 740514,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 13,
                'created_at' => '2016-11-12 05:04:49',
                'updated_at' => '2016-11-12 05:04:49',
            ),
            13 => 
            array (
                'id' => 24,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 8',
                'file_name' => 'olele 8.jpg',
                'disk' => 'media',
                'size' => 919737,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 14,
                'created_at' => '2016-11-12 05:04:55',
                'updated_at' => '2016-11-12 05:04:55',
            ),
            14 => 
            array (
                'id' => 25,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 1',
                'file_name' => 'pulau saronde 1.png',
                'disk' => 'media',
                'size' => 344332,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 15,
                'created_at' => '2016-11-12 05:05:10',
                'updated_at' => '2016-11-12 05:05:10',
            ),
            15 => 
            array (
                'id' => 26,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 2',
                'file_name' => 'pulau saronde 2.jpg',
                'disk' => 'media',
                'size' => 524190,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 16,
                'created_at' => '2016-11-12 05:05:14',
                'updated_at' => '2016-11-12 05:05:14',
            ),
            16 => 
            array (
                'id' => 27,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 3',
                'file_name' => 'pulau saronde 3.jpg',
                'disk' => 'media',
                'size' => 334660,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 17,
                'created_at' => '2016-11-12 05:05:17',
                'updated_at' => '2016-11-12 05:05:17',
            ),
            17 => 
            array (
                'id' => 28,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 4',
                'file_name' => 'pulau saronde 4.jpg',
                'disk' => 'media',
                'size' => 426504,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 18,
                'created_at' => '2016-11-12 05:05:20',
                'updated_at' => '2016-11-12 05:05:20',
            ),
            18 => 
            array (
                'id' => 29,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 5',
                'file_name' => 'pulau saronde 5.jpg',
                'disk' => 'media',
                'size' => 540436,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 19,
                'created_at' => '2016-11-12 05:05:24',
                'updated_at' => '2016-11-12 05:05:24',
            ),
            19 => 
            array (
                'id' => 30,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 6',
                'file_name' => 'pulau saronde 6.jpg',
                'disk' => 'media',
                'size' => 604629,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 20,
                'created_at' => '2016-11-12 05:05:26',
                'updated_at' => '2016-11-12 05:05:26',
            ),
            20 => 
            array (
                'id' => 31,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 1',
                'file_name' => 'diyonumo 1.jpg',
                'disk' => 'media',
                'size' => 414877,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 21,
                'created_at' => '2016-11-12 05:05:43',
                'updated_at' => '2016-11-12 05:05:43',
            ),
            21 => 
            array (
                'id' => 32,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 2',
                'file_name' => 'diyonumo 2.jpg',
                'disk' => 'media',
                'size' => 249392,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 22,
                'created_at' => '2016-11-12 05:05:46',
                'updated_at' => '2016-11-12 05:05:46',
            ),
            22 => 
            array (
                'id' => 33,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 3',
                'file_name' => 'diyonumo 3.jpg',
                'disk' => 'media',
                'size' => 181161,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 23,
                'created_at' => '2016-11-12 05:05:50',
                'updated_at' => '2016-11-12 05:05:50',
            ),
            23 => 
            array (
                'id' => 34,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 4',
                'file_name' => 'diyonumo 4.jpg',
                'disk' => 'media',
                'size' => 319829,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 24,
                'created_at' => '2016-11-12 05:05:54',
                'updated_at' => '2016-11-12 05:05:54',
            ),
            24 => 
            array (
                'id' => 35,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 5',
                'file_name' => 'diyonumo 5.jpg',
                'disk' => 'media',
                'size' => 896968,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 25,
                'created_at' => '2016-11-12 05:05:58',
                'updated_at' => '2016-11-12 05:05:58',
            ),
            25 => 
            array (
                'id' => 36,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 6',
                'file_name' => 'diyonumo 6.jpg',
                'disk' => 'media',
                'size' => 1129593,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 26,
                'created_at' => '2016-11-12 05:06:02',
                'updated_at' => '2016-11-12 05:06:02',
            ),
            26 => 
            array (
                'id' => 38,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 1',
                'file_name' => 'lombongo 1.jpg',
                'disk' => 'media',
                'size' => 558578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 27,
                'created_at' => '2016-11-12 05:09:46',
                'updated_at' => '2016-11-12 05:09:46',
            ),
            27 => 
            array (
                'id' => 39,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 2',
                'file_name' => 'lombongo 2.jpg',
                'disk' => 'media',
                'size' => 269764,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 28,
                'created_at' => '2016-11-12 05:09:55',
                'updated_at' => '2016-11-12 05:09:55',
            ),
            28 => 
            array (
                'id' => 40,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 3',
                'file_name' => 'lombongo 3.jpg',
                'disk' => 'media',
                'size' => 46394,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 29,
                'created_at' => '2016-11-12 05:09:58',
                'updated_at' => '2016-11-12 05:09:58',
            ),
            29 => 
            array (
                'id' => 41,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 4',
                'file_name' => 'lombongo 4.jpg',
                'disk' => 'media',
                'size' => 112146,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 30,
                'created_at' => '2016-11-12 05:10:02',
                'updated_at' => '2016-11-12 05:10:02',
            ),
            30 => 
            array (
                'id' => 42,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 5',
                'file_name' => 'lombongo 5.jpg',
                'disk' => 'media',
                'size' => 106908,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 31,
                'created_at' => '2016-11-12 05:10:05',
                'updated_at' => '2016-11-12 05:10:05',
            ),
            31 => 
            array (
                'id' => 43,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 6',
                'file_name' => 'lombongo 6.jpg',
                'disk' => 'media',
                'size' => 35045,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 32,
                'created_at' => '2016-11-12 05:10:09',
                'updated_at' => '2016-11-12 05:10:09',
            ),
            32 => 
            array (
                'id' => 44,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 7',
                'file_name' => 'lombongo 7.JPG',
                'disk' => 'media',
                'size' => 263319,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 33,
                'created_at' => '2016-11-12 05:10:13',
                'updated_at' => '2016-11-12 05:10:13',
            ),
            33 => 
            array (
                'id' => 46,
                'model_id' => 9,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Nani Wartabone',
                'name' => 'kaos nani wartabone',
                'file_name' => 'kaos nani wartabone.jpg',
                'disk' => 'media',
                'size' => 346727,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 34,
                'created_at' => '2016-11-16 11:15:52',
                'updated_at' => '2016-11-16 11:15:52',
            ),
            34 => 
            array (
                'id' => 47,
                'model_id' => 10,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos  GTO42 AITAKATA',
                'name' => 'kaos GTO42 AITAKATA',
                'file_name' => 'kaos GTO42 AITAKATA.jpg',
                'disk' => 'media',
                'size' => 1695756,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 35,
                'created_at' => '2016-11-16 11:16:15',
                'updated_at' => '2016-11-16 11:16:15',
            ),
            35 => 
            array (
                'id' => 48,
                'model_id' => 11,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Hero ti Pak Nani',
                'name' => 'kaos hero ti pak nani',
                'file_name' => 'kaos hero ti pak nani.jpg',
                'disk' => 'media',
                'size' => 251513,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 36,
                'created_at' => '2016-11-16 11:16:26',
                'updated_at' => '2016-11-16 11:16:26',
            ),
            36 => 
            array (
                'id' => 49,
                'model_id' => 12,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Proud Gorontalo',
                'name' => 'kaos pround gorontalo',
                'file_name' => 'kaos pround gorontalo.jpg',
                'disk' => 'media',
                'size' => 494124,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 37,
                'created_at' => '2016-11-16 11:17:18',
                'updated_at' => '2016-11-16 11:17:18',
            ),
            37 => 
            array (
                'id' => 50,
                'model_id' => 13,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaso awake in gorontalo',
                'name' => 'kaos awake in gorontalo',
                'file_name' => 'kaos awake in gorontalo.jpg',
                'disk' => 'media',
                'size' => 336808,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 38,
                'created_at' => '2016-11-16 11:17:33',
                'updated_at' => '2016-11-16 11:17:33',
            ),
            38 => 
            array (
                'id' => 51,
                'model_id' => 14,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Milu Siram',
                'name' => 'kaos milu siram',
                'file_name' => 'kaos milu siram.jpg',
                'disk' => 'media',
                'size' => 406729,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 39,
                'created_at' => '2016-11-16 11:21:08',
                'updated_at' => '2016-11-16 11:21:08',
            ),
            39 => 
            array (
                'id' => 52,
                'model_id' => 15,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos MTMA Gorontalo',
                'name' => 'kaos mtm gorontalo',
                'file_name' => 'kaos mtm gorontalo.jpg',
                'disk' => 'media',
                'size' => 591176,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 40,
                'created_at' => '2016-11-16 11:21:26',
                'updated_at' => '2016-11-16 11:21:26',
            ),
            40 => 
            array (
                'id' => 53,
                'model_id' => 16,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Mini Makuta',
                'name' => 'kaos mini makuta',
                'file_name' => 'kaos mini makuta.jpg',
                'disk' => 'media',
                'size' => 415424,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 41,
                'created_at' => '2016-11-16 11:21:43',
                'updated_at' => '2016-11-16 11:21:43',
            ),
            41 => 
            array (
                'id' => 54,
                'model_id' => 17,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Hoode MTMA Gorontalo',
                'name' => 'hoode mtma gorontalo',
                'file_name' => 'hoode mtma gorontalo.jpg',
                'disk' => 'media',
                'size' => 522207,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 42,
                'created_at' => '2016-11-16 11:21:59',
                'updated_at' => '2016-11-16 11:21:59',
            ),
            42 => 
            array (
                'id' => 55,
                'model_id' => 18,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos iG Gorontalo',
                'name' => 'kaos ig gorontalo',
                'file_name' => 'kaos ig gorontalo.jpg',
                'disk' => 'media',
                'size' => 495727,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 43,
                'created_at' => '2016-11-16 11:22:12',
                'updated_at' => '2016-11-16 11:22:12',
            ),
            43 => 
            array (
                'id' => 56,
                'model_id' => 19,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Padeti Ismail',
                'name' => 'kaos padeti ismail',
                'file_name' => 'kaos padeti ismail.jpg',
                'disk' => 'media',
                'size' => 447414,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 44,
                'created_at' => '2016-11-16 11:27:56',
                'updated_at' => '2016-11-16 11:27:56',
            ),
            44 => 
            array (
                'id' => 57,
                'model_id' => 20,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Instanusantara Gorontalo',
                'name' => 'kaos instanusantara gorontalo',
                'file_name' => 'kaos instanusantara gorontalo.jpg',
                'disk' => 'media',
                'size' => 383514,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 45,
                'created_at' => '2016-11-16 11:28:15',
                'updated_at' => '2016-11-16 11:28:15',
            ),
            45 => 
            array (
                'id' => 58,
                'model_id' => 21,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Hede I Love Gorontalo',
                'name' => 'kaos hede i love gorontalo',
                'file_name' => 'kaos hede i love gorontalo.jpg',
                'disk' => 'media',
                'size' => 470379,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 46,
                'created_at' => '2016-11-16 11:28:27',
                'updated_at' => '2016-11-16 11:28:27',
            ),
            46 => 
            array (
                'id' => 59,
                'model_id' => 22,
                'model_type' => 'App\Kaos',
                'collection_name' => 'Kaos Mini Makuta',
                'name' => 'kaos mini makuta',
                'file_name' => 'kaos mini makuta.jpg',
                'disk' => 'media',
                'size' => 415424,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 47,
                'created_at' => '2016-11-16 11:28:37',
                'updated_at' => '2016-11-16 11:28:37',
            ),
            47 => 
            array (
                'id' => 60,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'menara',
                'file_name' => 'menara.jpg',
                'disk' => 'media',
                'size' => 78352,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 48,
                'created_at' => '2016-11-16 13:30:02',
                'updated_at' => '2016-11-16 13:30:02',
            ),
            48 => 
            array (
                'id' => 61,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'bantayo',
                'file_name' => 'bantayo.jpg',
                'disk' => 'media',
                'size' => 57953,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 49,
                'created_at' => '2016-11-16 13:30:09',
                'updated_at' => '2016-11-16 13:30:09',
            ),
            49 => 
            array (
                'id' => 62,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'kotagorontalo',
                'file_name' => 'kotagorontalo.jpg',
                'disk' => 'media',
                'size' => 72821,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 50,
                'created_at' => '2016-11-16 13:30:14',
                'updated_at' => '2016-11-16 13:30:14',
            ),
            50 => 
            array (
                'id' => 63,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'pendaratan',
                'file_name' => 'pendaratan.jpg',
                'disk' => 'media',
                'size' => 207163,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 51,
                'created_at' => '2016-11-16 13:30:22',
                'updated_at' => '2016-11-16 13:30:22',
            ),
            51 => 
            array (
                'id' => 64,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'otanaha',
                'file_name' => 'otanaha.jpg',
                'disk' => 'media',
                'size' => 172451,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 52,
                'created_at' => '2016-11-16 13:30:26',
                'updated_at' => '2016-11-16 13:30:26',
            ),
            52 => 
            array (
                'id' => 65,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'ilabulo',
                'file_name' => 'ilabulo.jpg',
                'disk' => 'media',
                'size' => 46366,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 53,
                'created_at' => '2016-11-16 13:30:32',
                'updated_at' => '2016-11-16 13:30:32',
            ),
            53 => 
            array (
                'id' => 66,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'KAMAR TIDUR',
                'file_name' => 'KAMAR TIDUR.jpg',
                'disk' => 'media',
                'size' => 56592,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 54,
                'created_at' => '2016-11-17 12:30:23',
                'updated_at' => '2016-11-17 12:30:23',
            ),
            54 => 
            array (
                'id' => 67,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_161048',
                'file_name' => 'IMG_20160921_161048.jpg',
                'disk' => 'media',
                'size' => 797710,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 55,
                'created_at' => '2016-11-19 13:34:15',
                'updated_at' => '2016-11-19 13:34:15',
            ),
            55 => 
            array (
                'id' => 68,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_161237',
                'file_name' => 'IMG_20160921_161237.jpg',
                'disk' => 'media',
                'size' => 793221,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 56,
                'created_at' => '2016-11-19 13:34:23',
                'updated_at' => '2016-11-19 13:34:23',
            ),
            56 => 
            array (
                'id' => 69,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_161322',
                'file_name' => 'IMG_20160921_161322.jpg',
                'disk' => 'media',
                'size' => 738020,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 57,
                'created_at' => '2016-11-19 13:34:27',
                'updated_at' => '2016-11-19 13:34:27',
            ),
            57 => 
            array (
                'id' => 70,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_161516',
                'file_name' => 'IMG_20160921_161516.jpg',
                'disk' => 'media',
                'size' => 679322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 58,
                'created_at' => '2016-11-19 13:34:31',
                'updated_at' => '2016-11-19 13:34:31',
            ),
            58 => 
            array (
                'id' => 71,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162350',
                'file_name' => 'IMG_20160921_162350.jpg',
                'disk' => 'media',
                'size' => 684512,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 59,
                'created_at' => '2016-11-19 13:34:35',
                'updated_at' => '2016-11-19 13:34:35',
            ),
            59 => 
            array (
                'id' => 72,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162420',
                'file_name' => 'IMG_20160921_162420.jpg',
                'disk' => 'media',
                'size' => 640265,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 60,
                'created_at' => '2016-11-19 13:34:39',
                'updated_at' => '2016-11-19 13:34:39',
            ),
            60 => 
            array (
                'id' => 73,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162452',
                'file_name' => 'IMG_20160921_162452.jpg',
                'disk' => 'media',
                'size' => 654914,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 61,
                'created_at' => '2016-11-19 13:34:49',
                'updated_at' => '2016-11-19 13:34:49',
            ),
            61 => 
            array (
                'id' => 74,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162534',
                'file_name' => 'IMG_20160921_162534.jpg',
                'disk' => 'media',
                'size' => 696627,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 62,
                'created_at' => '2016-11-19 13:34:53',
                'updated_at' => '2016-11-19 13:34:53',
            ),
            62 => 
            array (
                'id' => 75,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162601',
                'file_name' => 'IMG_20160921_162601.jpg',
                'disk' => 'media',
                'size' => 690165,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 63,
                'created_at' => '2016-11-19 13:34:56',
                'updated_at' => '2016-11-19 13:34:56',
            ),
            63 => 
            array (
                'id' => 76,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162630',
                'file_name' => 'IMG_20160921_162630.jpg',
                'disk' => 'media',
                'size' => 716307,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 64,
                'created_at' => '2016-11-19 13:35:05',
                'updated_at' => '2016-11-19 13:35:05',
            ),
            64 => 
            array (
                'id' => 77,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162655',
                'file_name' => 'IMG_20160921_162655.jpg',
                'disk' => 'media',
                'size' => 955956,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 65,
                'created_at' => '2016-11-19 13:35:14',
                'updated_at' => '2016-11-19 13:35:14',
            ),
            65 => 
            array (
                'id' => 78,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162718',
                'file_name' => 'IMG_20160921_162718.jpg',
                'disk' => 'media',
                'size' => 711500,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 66,
                'created_at' => '2016-11-19 13:35:23',
                'updated_at' => '2016-11-19 13:35:23',
            ),
            66 => 
            array (
                'id' => 79,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162741',
                'file_name' => 'IMG_20160921_162741.jpg',
                'disk' => 'media',
                'size' => 763037,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 67,
                'created_at' => '2016-11-19 13:35:31',
                'updated_at' => '2016-11-19 13:35:31',
            ),
            67 => 
            array (
                'id' => 80,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162817',
                'file_name' => 'IMG_20160921_162817.jpg',
                'disk' => 'media',
                'size' => 579283,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 68,
                'created_at' => '2016-11-19 13:35:39',
                'updated_at' => '2016-11-19 13:35:39',
            ),
            68 => 
            array (
                'id' => 81,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162842',
                'file_name' => 'IMG_20160921_162842.jpg',
                'disk' => 'media',
                'size' => 503048,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 69,
                'created_at' => '2016-11-19 13:35:45',
                'updated_at' => '2016-11-19 13:35:45',
            ),
            69 => 
            array (
                'id' => 82,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162906',
                'file_name' => 'IMG_20160921_162906.jpg',
                'disk' => 'media',
                'size' => 631920,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 70,
                'created_at' => '2016-11-19 13:35:54',
                'updated_at' => '2016-11-19 13:35:54',
            ),
            70 => 
            array (
                'id' => 83,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_162947',
                'file_name' => 'IMG_20160921_162947.jpg',
                'disk' => 'media',
                'size' => 724007,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 71,
                'created_at' => '2016-11-19 13:36:17',
                'updated_at' => '2016-11-19 13:36:17',
            ),
            71 => 
            array (
                'id' => 84,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163014',
                'file_name' => 'IMG_20160921_163014.jpg',
                'disk' => 'media',
                'size' => 686677,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 72,
                'created_at' => '2016-11-19 13:36:23',
                'updated_at' => '2016-11-19 13:36:23',
            ),
            72 => 
            array (
                'id' => 85,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163058',
                'file_name' => 'IMG_20160921_163058.jpg',
                'disk' => 'media',
                'size' => 842293,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 73,
                'created_at' => '2016-11-19 13:36:39',
                'updated_at' => '2016-11-19 13:36:39',
            ),
            73 => 
            array (
                'id' => 86,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163200',
                'file_name' => 'IMG_20160921_163200.jpg',
                'disk' => 'media',
                'size' => 639090,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 74,
                'created_at' => '2016-11-19 13:36:43',
                'updated_at' => '2016-11-19 13:36:43',
            ),
            74 => 
            array (
                'id' => 87,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163227',
                'file_name' => 'IMG_20160921_163227.jpg',
                'disk' => 'media',
                'size' => 695707,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 75,
                'created_at' => '2016-11-19 13:36:48',
                'updated_at' => '2016-11-19 13:36:48',
            ),
            75 => 
            array (
                'id' => 88,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163321',
                'file_name' => 'IMG_20160921_163321.jpg',
                'disk' => 'media',
                'size' => 619120,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 76,
                'created_at' => '2016-11-19 13:36:55',
                'updated_at' => '2016-11-19 13:36:55',
            ),
            76 => 
            array (
                'id' => 89,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163342',
                'file_name' => 'IMG_20160921_163342.jpg',
                'disk' => 'media',
                'size' => 451261,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 77,
                'created_at' => '2016-11-19 13:37:00',
                'updated_at' => '2016-11-19 13:37:00',
            ),
            77 => 
            array (
                'id' => 90,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163414',
                'file_name' => 'IMG_20160921_163414.jpg',
                'disk' => 'media',
                'size' => 516319,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 78,
                'created_at' => '2016-11-19 13:37:05',
                'updated_at' => '2016-11-19 13:37:05',
            ),
            78 => 
            array (
                'id' => 91,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163519',
                'file_name' => 'IMG_20160921_163519.jpg',
                'disk' => 'media',
                'size' => 483175,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 79,
                'created_at' => '2016-11-19 13:37:09',
                'updated_at' => '2016-11-19 13:37:09',
            ),
            79 => 
            array (
                'id' => 92,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163547',
                'file_name' => 'IMG_20160921_163547.jpg',
                'disk' => 'media',
                'size' => 347243,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 80,
                'created_at' => '2016-11-19 13:37:20',
                'updated_at' => '2016-11-19 13:37:20',
            ),
            80 => 
            array (
                'id' => 93,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163619',
                'file_name' => 'IMG_20160921_163619.jpg',
                'disk' => 'media',
                'size' => 670824,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 81,
                'created_at' => '2016-11-19 13:37:24',
                'updated_at' => '2016-11-19 13:37:24',
            ),
            81 => 
            array (
                'id' => 94,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163642',
                'file_name' => 'IMG_20160921_163642.jpg',
                'disk' => 'media',
                'size' => 590880,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 82,
                'created_at' => '2016-11-19 13:37:28',
                'updated_at' => '2016-11-19 13:37:28',
            ),
            82 => 
            array (
                'id' => 95,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163709',
                'file_name' => 'IMG_20160921_163709.jpg',
                'disk' => 'media',
                'size' => 507688,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 83,
                'created_at' => '2016-11-19 13:37:33',
                'updated_at' => '2016-11-19 13:37:33',
            ),
            83 => 
            array (
                'id' => 96,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163807',
                'file_name' => 'IMG_20160921_163807.jpg',
                'disk' => 'media',
                'size' => 342079,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 84,
                'created_at' => '2016-11-19 13:37:36',
                'updated_at' => '2016-11-19 13:37:36',
            ),
            84 => 
            array (
                'id' => 97,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_163836',
                'file_name' => 'IMG_20160921_163836.jpg',
                'disk' => 'media',
                'size' => 791395,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 85,
                'created_at' => '2016-11-19 13:37:40',
                'updated_at' => '2016-11-19 13:37:40',
            ),
            85 => 
            array (
                'id' => 98,
                'model_id' => 1,
                'model_type' => 'App\Gallery',
                'collection_name' => 'gallery',
                'name' => 'IMG_20160921_164015',
                'file_name' => 'IMG_20160921_164015.jpg',
                'disk' => 'media',
                'size' => 617747,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 86,
                'created_at' => '2016-11-19 13:37:44',
                'updated_at' => '2016-11-19 13:37:44',
            ),
        ));
        
        
    }
}
