<?php

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_id' => 1,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 1',
                'file_name' => 'pulo cinta 1.png',
                'disk' => 'media',
                'size' => 415203,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 1,
                'created_at' => '2016-11-30 23:07:53',
                'updated_at' => '2016-11-30 23:07:53',
            ),
            1 => 
            array (
                'id' => 2,
                'model_id' => 1,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 2',
                'file_name' => 'pulo cinta 2.jpg',
                'disk' => 'media',
                'size' => 359342,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 2,
                'created_at' => '2016-11-30 23:10:00',
                'updated_at' => '2016-11-30 23:10:00',
            ),
            2 => 
            array (
                'id' => 3,
                'model_id' => 1,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 3',
                'file_name' => 'pulo cinta 3.jpg',
                'disk' => 'media',
                'size' => 404322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 3,
                'created_at' => '2016-11-30 23:10:03',
                'updated_at' => '2016-11-30 23:10:03',
            ),
            3 => 
            array (
                'id' => 4,
                'model_id' => 1,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 4',
                'file_name' => 'pulo cinta 4.jpg',
                'disk' => 'media',
                'size' => 417741,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 4,
                'created_at' => '2016-11-30 23:10:06',
                'updated_at' => '2016-11-30 23:10:06',
            ),
            4 => 
            array (
                'id' => 5,
                'model_id' => 1,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 5',
                'file_name' => 'pulo cinta 5.jpg',
                'disk' => 'media',
                'size' => 687729,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 5,
                'created_at' => '2016-11-30 23:10:10',
                'updated_at' => '2016-11-30 23:10:10',
            ),
            5 => 
            array (
                'id' => 6,
                'model_id' => 2,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 1',
                'file_name' => 'olele 1.jpg',
                'disk' => 'media',
                'size' => 58030,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 6,
                'created_at' => '2016-11-30 23:10:27',
                'updated_at' => '2016-11-30 23:10:27',
            ),
            6 => 
            array (
                'id' => 7,
                'model_id' => 2,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 2',
                'file_name' => 'olele 2.jpg',
                'disk' => 'media',
                'size' => 387887,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 7,
                'created_at' => '2016-11-30 23:10:30',
                'updated_at' => '2016-11-30 23:10:30',
            ),
            7 => 
            array (
                'id' => 8,
                'model_id' => 2,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 3',
                'file_name' => 'olele 3.jpg',
                'disk' => 'media',
                'size' => 133272,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 8,
                'created_at' => '2016-11-30 23:10:33',
                'updated_at' => '2016-11-30 23:10:33',
            ),
            8 => 
            array (
                'id' => 9,
                'model_id' => 2,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 4',
                'file_name' => 'olele 4.jpg',
                'disk' => 'media',
                'size' => 371159,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 9,
                'created_at' => '2016-11-30 23:10:36',
                'updated_at' => '2016-11-30 23:10:36',
            ),
            9 => 
            array (
                'id' => 10,
                'model_id' => 2,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 5',
                'file_name' => 'olele 5.jpg',
                'disk' => 'media',
                'size' => 642926,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 10,
                'created_at' => '2016-11-30 23:10:40',
                'updated_at' => '2016-11-30 23:10:40',
            ),
            10 => 
            array (
                'id' => 11,
                'model_id' => 3,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 1',
                'file_name' => 'pulau saronde 1.png',
                'disk' => 'media',
                'size' => 344332,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 11,
                'created_at' => '2016-11-30 23:10:48',
                'updated_at' => '2016-11-30 23:10:48',
            ),
            11 => 
            array (
                'id' => 12,
                'model_id' => 3,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 2',
                'file_name' => 'pulau saronde 2.jpg',
                'disk' => 'media',
                'size' => 524190,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 12,
                'created_at' => '2016-11-30 23:10:51',
                'updated_at' => '2016-11-30 23:10:51',
            ),
            12 => 
            array (
                'id' => 13,
                'model_id' => 3,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 3',
                'file_name' => 'pulau saronde 3.jpg',
                'disk' => 'media',
                'size' => 334660,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 13,
                'created_at' => '2016-11-30 23:10:53',
                'updated_at' => '2016-11-30 23:10:53',
            ),
            13 => 
            array (
                'id' => 14,
                'model_id' => 3,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 4',
                'file_name' => 'pulau saronde 4.jpg',
                'disk' => 'media',
                'size' => 426504,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 14,
                'created_at' => '2016-11-30 23:10:55',
                'updated_at' => '2016-11-30 23:10:55',
            ),
            14 => 
            array (
                'id' => 15,
                'model_id' => 3,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 6',
                'file_name' => 'pulau saronde 6.jpg',
                'disk' => 'media',
                'size' => 604629,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 15,
                'created_at' => '2016-11-30 23:10:58',
                'updated_at' => '2016-11-30 23:10:58',
            ),
            15 => 
            array (
                'id' => 16,
                'model_id' => 4,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 1',
                'file_name' => 'diyonumo 1.jpg',
                'disk' => 'media',
                'size' => 414877,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 16,
                'created_at' => '2016-11-30 23:11:08',
                'updated_at' => '2016-11-30 23:11:08',
            ),
            16 => 
            array (
                'id' => 17,
                'model_id' => 4,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 2',
                'file_name' => 'diyonumo 2.jpg',
                'disk' => 'media',
                'size' => 249392,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 17,
                'created_at' => '2016-11-30 23:11:10',
                'updated_at' => '2016-11-30 23:11:10',
            ),
            17 => 
            array (
                'id' => 18,
                'model_id' => 4,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 3',
                'file_name' => 'diyonumo 3.jpg',
                'disk' => 'media',
                'size' => 181161,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 18,
                'created_at' => '2016-11-30 23:11:13',
                'updated_at' => '2016-11-30 23:11:13',
            ),
            18 => 
            array (
                'id' => 19,
                'model_id' => 4,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 4',
                'file_name' => 'diyonumo 4.jpg',
                'disk' => 'media',
                'size' => 319829,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 19,
                'created_at' => '2016-11-30 23:11:16',
                'updated_at' => '2016-11-30 23:11:16',
            ),
            19 => 
            array (
                'id' => 20,
                'model_id' => 4,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 5',
                'file_name' => 'diyonumo 5.jpg',
                'disk' => 'media',
                'size' => 896968,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 20,
                'created_at' => '2016-11-30 23:11:20',
                'updated_at' => '2016-11-30 23:11:20',
            ),
            20 => 
            array (
                'id' => 21,
                'model_id' => 5,
                'model_type' => 'App\\Tour',
                'collection_name' => 'City Tour',
                'name' => 'bantayo',
                'file_name' => 'bantayo.jpg',
                'disk' => 'media',
                'size' => 57953,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 21,
                'created_at' => '2016-11-30 23:11:30',
                'updated_at' => '2016-11-30 23:11:30',
            ),
            21 => 
            array (
                'id' => 22,
                'model_id' => 5,
                'model_type' => 'App\\Tour',
                'collection_name' => 'City Tour',
                'name' => 'menara',
                'file_name' => 'menara.jpg',
                'disk' => 'media',
                'size' => 78352,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 22,
                'created_at' => '2016-11-30 23:11:34',
                'updated_at' => '2016-11-30 23:11:34',
            ),
            22 => 
            array (
                'id' => 23,
                'model_id' => 5,
                'model_type' => 'App\\Tour',
                'collection_name' => 'City Tour',
                'name' => 'otanaha',
                'file_name' => 'otanaha.jpg',
                'disk' => 'media',
                'size' => 172451,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 23,
                'created_at' => '2016-11-30 23:11:37',
                'updated_at' => '2016-11-30 23:11:37',
            ),
            23 => 
            array (
                'id' => 24,
                'model_id' => 5,
                'model_type' => 'App\\Tour',
                'collection_name' => 'City Tour',
                'name' => 'pendaratan',
                'file_name' => 'pendaratan.jpg',
                'disk' => 'media',
                'size' => 207163,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 24,
                'created_at' => '2016-11-30 23:11:40',
                'updated_at' => '2016-11-30 23:11:40',
            ),
            24 => 
            array (
                'id' => 25,
                'model_id' => 5,
                'model_type' => 'App\\Tour',
                'collection_name' => 'City Tour',
                'name' => 'kotagorontalo',
                'file_name' => 'kotagorontalo.jpg',
                'disk' => 'media',
                'size' => 72821,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 25,
                'created_at' => '2016-11-30 23:11:43',
                'updated_at' => '2016-11-30 23:11:43',
            ),
            25 => 
            array (
                'id' => 26,
                'model_id' => 6,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 1',
                'file_name' => 'lombongo 1.jpg',
                'disk' => 'media',
                'size' => 558578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 26,
                'created_at' => '2016-11-30 23:11:52',
                'updated_at' => '2016-11-30 23:11:52',
            ),
            26 => 
            array (
                'id' => 27,
                'model_id' => 6,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 2',
                'file_name' => 'lombongo 2.jpg',
                'disk' => 'media',
                'size' => 269764,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 27,
                'created_at' => '2016-11-30 23:11:59',
                'updated_at' => '2016-11-30 23:11:59',
            ),
            27 => 
            array (
                'id' => 28,
                'model_id' => 6,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 3',
                'file_name' => 'lombongo 3.jpg',
                'disk' => 'media',
                'size' => 46394,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 28,
                'created_at' => '2016-11-30 23:12:02',
                'updated_at' => '2016-11-30 23:12:02',
            ),
            28 => 
            array (
                'id' => 29,
                'model_id' => 6,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 5',
                'file_name' => 'lombongo 5.jpg',
                'disk' => 'media',
                'size' => 106908,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 29,
                'created_at' => '2016-11-30 23:12:05',
                'updated_at' => '2016-11-30 23:12:05',
            ),
            29 => 
            array (
                'id' => 30,
                'model_id' => 6,
                'model_type' => 'App\\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 6',
                'file_name' => 'lombongo 6.jpg',
                'disk' => 'media',
                'size' => 35045,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 30,
                'created_at' => '2016-11-30 23:12:08',
                'updated_at' => '2016-11-30 23:12:08',
            ),
        ));
        
        
    }
}
