<?php

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 105,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 1',
                'file_name' => 'pulo cinta 1.png',
                'disk' => 'media',
                'size' => 415203,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 1,
                'created_at' => '2016-11-30 22:08:32',
                'updated_at' => '2016-11-30 22:08:32',
            ),
            1 => 
            array (
                'id' => 106,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 2',
                'file_name' => 'pulo cinta 2.jpg',
                'disk' => 'media',
                'size' => 359342,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 2,
                'created_at' => '2016-11-30 22:08:38',
                'updated_at' => '2016-11-30 22:08:38',
            ),
            2 => 
            array (
                'id' => 107,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 3',
                'file_name' => 'pulo cinta 3.jpg',
                'disk' => 'media',
                'size' => 404322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 3,
                'created_at' => '2016-11-30 22:08:41',
                'updated_at' => '2016-11-30 22:08:41',
            ),
            3 => 
            array (
                'id' => 108,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 4',
                'file_name' => 'pulo cinta 4.jpg',
                'disk' => 'media',
                'size' => 417741,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 4,
                'created_at' => '2016-11-30 22:08:45',
                'updated_at' => '2016-11-30 22:08:45',
            ),
            4 => 
            array (
                'id' => 109,
                'model_id' => 1,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulo Cinta',
                'name' => 'pulo cinta 5',
                'file_name' => 'pulo cinta 5.jpg',
                'disk' => 'media',
                'size' => 687729,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 5,
                'created_at' => '2016-11-30 22:08:49',
                'updated_at' => '2016-11-30 22:08:49',
            ),
            5 => 
            array (
                'id' => 110,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 1',
                'file_name' => 'olele 1.jpg',
                'disk' => 'media',
                'size' => 58030,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 6,
                'created_at' => '2016-11-30 22:09:08',
                'updated_at' => '2016-11-30 22:09:08',
            ),
            6 => 
            array (
                'id' => 111,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 2',
                'file_name' => 'olele 2.jpg',
                'disk' => 'media',
                'size' => 387887,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 7,
                'created_at' => '2016-11-30 22:09:10',
                'updated_at' => '2016-11-30 22:09:10',
            ),
            7 => 
            array (
                'id' => 112,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 3',
                'file_name' => 'olele 3.jpg',
                'disk' => 'media',
                'size' => 133272,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 8,
                'created_at' => '2016-11-30 22:09:13',
                'updated_at' => '2016-11-30 22:09:13',
            ),
            8 => 
            array (
                'id' => 113,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 4',
                'file_name' => 'olele 4.jpg',
                'disk' => 'media',
                'size' => 371159,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 9,
                'created_at' => '2016-11-30 22:09:16',
                'updated_at' => '2016-11-30 22:09:16',
            ),
            9 => 
            array (
                'id' => 114,
                'model_id' => 2,
                'model_type' => 'App\Tour',
                'collection_name' => 'Taman laut olele',
                'name' => 'olele 6',
                'file_name' => 'olele 6.jpg',
                'disk' => 'media',
                'size' => 482974,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 10,
                'created_at' => '2016-11-30 22:09:19',
                'updated_at' => '2016-11-30 22:09:19',
            ),
            10 => 
            array (
                'id' => 115,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 1',
                'file_name' => 'pulau saronde 1.png',
                'disk' => 'media',
                'size' => 344332,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 11,
                'created_at' => '2016-11-30 22:09:30',
                'updated_at' => '2016-11-30 22:09:30',
            ),
            11 => 
            array (
                'id' => 116,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 2',
                'file_name' => 'pulau saronde 2.jpg',
                'disk' => 'media',
                'size' => 524190,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 12,
                'created_at' => '2016-11-30 22:09:33',
                'updated_at' => '2016-11-30 22:09:33',
            ),
            12 => 
            array (
                'id' => 117,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 3',
                'file_name' => 'pulau saronde 3.jpg',
                'disk' => 'media',
                'size' => 334660,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 13,
                'created_at' => '2016-11-30 22:09:36',
                'updated_at' => '2016-11-30 22:09:36',
            ),
            13 => 
            array (
                'id' => 118,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 4',
                'file_name' => 'pulau saronde 4.jpg',
                'disk' => 'media',
                'size' => 426504,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 14,
                'created_at' => '2016-11-30 22:09:38',
                'updated_at' => '2016-11-30 22:09:38',
            ),
            14 => 
            array (
                'id' => 119,
                'model_id' => 3,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau saronde',
                'name' => 'pulau saronde 6',
                'file_name' => 'pulau saronde 6.jpg',
                'disk' => 'media',
                'size' => 604629,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 15,
                'created_at' => '2016-11-30 22:09:41',
                'updated_at' => '2016-11-30 22:09:41',
            ),
            15 => 
            array (
                'id' => 120,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 1',
                'file_name' => 'diyonumo 1.jpg',
                'disk' => 'media',
                'size' => 414877,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 16,
                'created_at' => '2016-11-30 22:09:51',
                'updated_at' => '2016-11-30 22:09:51',
            ),
            16 => 
            array (
                'id' => 121,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 2',
                'file_name' => 'diyonumo 2.jpg',
                'disk' => 'media',
                'size' => 249392,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 17,
                'created_at' => '2016-11-30 22:09:53',
                'updated_at' => '2016-11-30 22:09:53',
            ),
            17 => 
            array (
                'id' => 122,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 3',
                'file_name' => 'diyonumo 3.jpg',
                'disk' => 'media',
                'size' => 181161,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 18,
                'created_at' => '2016-11-30 22:09:57',
                'updated_at' => '2016-11-30 22:09:57',
            ),
            18 => 
            array (
                'id' => 123,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 4',
                'file_name' => 'diyonumo 4.jpg',
                'disk' => 'media',
                'size' => 319829,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 19,
                'created_at' => '2016-11-30 22:09:59',
                'updated_at' => '2016-11-30 22:09:59',
            ),
            19 => 
            array (
                'id' => 124,
                'model_id' => 4,
                'model_type' => 'App\Tour',
                'collection_name' => 'Pulau diyonumo',
                'name' => 'diyonumo 6',
                'file_name' => 'diyonumo 6.jpg',
                'disk' => 'media',
                'size' => 1129593,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 20,
                'created_at' => '2016-11-30 22:10:02',
                'updated_at' => '2016-11-30 22:10:02',
            ),
            20 => 
            array (
                'id' => 125,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'bantayo',
                'file_name' => 'bantayo.jpg',
                'disk' => 'media',
                'size' => 57953,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 21,
                'created_at' => '2016-11-30 22:10:13',
                'updated_at' => '2016-11-30 22:10:13',
            ),
            21 => 
            array (
                'id' => 126,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'menara',
                'file_name' => 'menara.jpg',
                'disk' => 'media',
                'size' => 78352,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 22,
                'created_at' => '2016-11-30 22:10:18',
                'updated_at' => '2016-11-30 22:10:18',
            ),
            22 => 
            array (
                'id' => 127,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'otanaha',
                'file_name' => 'otanaha.jpg',
                'disk' => 'media',
                'size' => 172451,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 23,
                'created_at' => '2016-11-30 22:10:20',
                'updated_at' => '2016-11-30 22:10:20',
            ),
            23 => 
            array (
                'id' => 128,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'pendaratan',
                'file_name' => 'pendaratan.jpg',
                'disk' => 'media',
                'size' => 207163,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 24,
                'created_at' => '2016-11-30 22:10:23',
                'updated_at' => '2016-11-30 22:10:23',
            ),
            24 => 
            array (
                'id' => 129,
                'model_id' => 5,
                'model_type' => 'App\Tour',
                'collection_name' => 'City Tour',
                'name' => 'kotagorontalo',
                'file_name' => 'kotagorontalo.jpg',
                'disk' => 'media',
                'size' => 72821,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 25,
                'created_at' => '2016-11-30 22:10:27',
                'updated_at' => '2016-11-30 22:10:27',
            ),
            25 => 
            array (
                'id' => 130,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 1',
                'file_name' => 'lombongo 1.jpg',
                'disk' => 'media',
                'size' => 558578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 26,
                'created_at' => '2016-11-30 22:10:38',
                'updated_at' => '2016-11-30 22:10:38',
            ),
            26 => 
            array (
                'id' => 131,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 3',
                'file_name' => 'lombongo 3.jpg',
                'disk' => 'media',
                'size' => 46394,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 27,
                'created_at' => '2016-11-30 22:10:48',
                'updated_at' => '2016-11-30 22:10:48',
            ),
            27 => 
            array (
                'id' => 132,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 5',
                'file_name' => 'lombongo 5.jpg',
                'disk' => 'media',
                'size' => 106908,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 28,
                'created_at' => '2016-11-30 22:10:51',
                'updated_at' => '2016-11-30 22:10:51',
            ),
            28 => 
            array (
                'id' => 133,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 2',
                'file_name' => 'lombongo 2.jpg',
                'disk' => 'media',
                'size' => 269764,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 29,
                'created_at' => '2016-11-30 22:10:54',
                'updated_at' => '2016-11-30 22:10:54',
            ),
            29 => 
            array (
                'id' => 134,
                'model_id' => 6,
                'model_type' => 'App\Tour',
                'collection_name' => 'Air terjun lombongo',
                'name' => 'lombongo 4',
                'file_name' => 'lombongo 4.jpg',
                'disk' => 'media',
                'size' => 112146,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'order_column' => 30,
                'created_at' => '2016-11-30 22:10:57',
                'updated_at' => '2016-11-30 22:10:57',
            ),
        ));
        
        
    }
}
